name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  check-version:
    name: Check if version changed in package.json
    runs-on: ubuntu-latest
    
    outputs:
      changed: ${{steps.check.outputs.changed}}
      version: ${{steps.check.outputs.version}}
      type: ${{steps.check.outputs.type}}
    
    steps:
    - uses: actions/checkout@v3
    - name: Check if version has been updated
      id: check
      uses: EndBug/version-check@v1
      with:
        diff-search: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Log when changed
      if: steps.check.outputs.changed == 'true'
      run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'
      
    - name: Log when unchanged
      if: steps.check.outputs.changed == 'false'
      run: 'echo "No version change :/"'

  build-and-package:
    name: Build and package application
    needs: [check-version]
    #if: needs.check-version.outputs.changed == 'true'

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - name: download wix toolset; `light.exe` and `candle.exe`
      uses: robinraju/release-downloader@v1.5
      with: 
        repository: "wixtoolset/wix3"
        latest: true
        fileName: "wix311-binaries.zip"
        
    - name: install candle and light
      run: |
        tar -xf wix311-binaries.zip
        $env:PATH += ";D:\a\SECRYPTLY\SECRYPTLY\wix311-binaries\"
        
    - run: candle
    - run: light
      
        
    - name: npm install, build, and package
      run: |
        npm install
        npm run build:prod
        npm run make

    - name: Upload artifact for deployment and release
      uses: actions/upload-artifact@v3
      with:
        name: secryptly-win32-x64.msi
        path: ./out/make/wix/x64/secryptly.msi
    
    
