name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  check-version:
    name: Check if version changed in package.json
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Check if version has been updated
      id: check
      uses: EndBug/version-check@v1
      with:
        diff-search: true
        token: ${{ secrets.GITHUB_TOKEN }}

  build-and-package:
    needs: check-version
    if: needs.check-version.steps.check.output.changed == 'true'

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - run: "echo ${{needs.check-version.steps.check.output}}"
    
    
